### ISSUE TITLE
Question: Does this module support indexing documents (Files?)

### ISSUE THREAD

**Issue by josephlewisnz** [wilr/silverstripe-algolia#48]
Question: Does this module support indexing documents (Files?)

From my understanding, there is also a limit on large indexing?

**Comment by wilr** [comment]
@josephlewisnz You can apply the Algolia object extension to any DataObject (which includes Files). Contents of files are not indexed. For that you should checkout Apache Tika or some other library to extract contents and push relevant terms to your Algolia index.

```
SilverStripe\Core\Injector\Injector:
  Wilr\SilverStripe\Algolia\Service\AlgoliaService:
    properties:
      adminApiKey: '`ALGOLIA_ADMIN_API_KEY`'
      searchApiKey: '`ALGOLIA_SEARCH_API_KEY`'
      applicationId: '`ALGOLIA_SEARCH_APP_ID`'
      indexes:
        IndexName:
          includeClasses:
            - SilverStripe\CMS\Model\SiteTree
            - SilverStripe\Assets\File
```
